name: follow the white rabbit.
on:
  push:
    tags: ['v*']
permissions:
  contents: write
jobs:
  release:
    uses: coryzibell/nebuchadnezzar/.github/workflows/follow-the-white-rabbit.yml@v1
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
